# Generated by Django 5.2.4 on 2025-07-28 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('message_data', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='published', max_length=50)),
            ],
            options={
                'verbose_name': 'Published Message',
                'verbose_name_plural': 'Published Messages',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subscription_name', models.CharField(max_length=255)),
                ('message_data', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Received Message',
                'verbose_name_plural': 'Received Messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
